title: Echo Music
icon: ../../../icons/Echo.png
background: ../../../icons/Echo.png
contents:
  - x: 448
    y: 344
    type: link
    path: /Applications
  - x: 192
    y: 344
    type: file
    path: Echo Music.app
window:
  size:
    width: 640
    height: 480

